# Generated by Django 3.0.2 on 2020-03-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('pupilo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=2)),
                ('matematica', models.CharField(max_length=50)),
                ('lenguaje', models.CharField(max_length=50)),
                ('historia', models.CharField(max_length=50)),
                ('ciencia', models.CharField(max_length=50)),
                ('ingles', models.CharField(max_length=50)),
                ('artes', models.CharField(max_length=50)),
                ('taller', models.CharField(max_length=50)),
                ('musica', models.CharField(max_length=50)),
                ('ed_fisica', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField()),
                ('email_contacto', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('num_emergencia', models.CharField(max_length=11)),
                ('curso', models.CharField(max_length=2)),
                ('apoderado', models.CharField(max_length=50)),
                ('trastorno', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nom_usuario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('ramos', multiselectfield.db.fields.MultiSelectField(choices=[('Matemáticas', 'Matemáticas'), ('Lenguaje', 'Lenguaje'), ('Historia', 'Historia'), ('Ciencia', 'Ciencias'), ('Ingles', 'Inglés'), ('Artes', 'Artes'), ('Taller', 'Taller'), ('Musica', 'Música'), ('Ed. Fisica', 'Ed. Física')], default='Matemáticas', max_length=75)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ramos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Estudiante')),
                ('tag', models.ManyToManyField(to='gestion.Tag')),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ramos', models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Lenguaje', 'Lenguaje'), ('Historia', 'Historia'), ('Ciencia', 'Ciencias'), ('Ingles', 'Inglés'), ('Artes', 'Artes'), ('Taller', 'Taller'), ('Musica', 'Música'), ('Ed. Fisica', 'Ed. Física')], default='Matemáticas', max_length=50)),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.Cursos')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Profesor')),
            ],
        ),
    ]
