# Generated by Django 3.0.2 on 2020-03-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ramos',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Lenguaje', 'Lenguaje'), ('Historia', 'Historia'), ('Ciencia', 'Ciencia'), ('Ingles', 'Ingles'), ('Artes', 'Artes'), ('Taller', 'Taller'), ('Musica', 'Musica'), ('Ed. Fisica', 'Ed. Fisica')], default='Matemática', max_length=50),
        ),
    ]
