# Generated by Django 3.0.2 on 2020-03-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='tag',
        ),
        migrations.AddField(
            model_name='notas',
            name='assignment',
            field=models.ManyToManyField(to='gestion.Assignment'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
