# Generated by Django 3.0.2 on 2020-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramos',
            name='ramo',
            field=models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Lenguaje', 'Lenguaje'), ('Historia', 'Historia'), ('Ciencias', 'Ciencias'), ('Inglés', 'Inglés'), ('Artes', 'Artes'), ('Taller', 'Taller'), ('Música', 'Música'), ('Ed. Física', 'Ed. Física')], default='Matemáticas', max_length=50),
        ),
    ]
