# Generated by Django 3.0.2 on 2020-03-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200325_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='artes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='artes', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='ciencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ciencia', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='ed_fisica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ed_fisica', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='historia', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='ingles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ingles', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='lenguaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lenguaje', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='matematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='matematica', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='musica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='musica', to='gestion.Profesor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='taller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='taller', to='gestion.Profesor'),
        ),
    ]
