# Generated by Django 3.0.2 on 2020-03-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_observaciones_ramos'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gestion.Cursos'),
        ),
    ]
