# Generated by Django 3.0.2 on 2020-03-24 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_observaciones_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='fecha_observacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
