# Generated by Django 3.0.2 on 2020-03-20 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='email',
            new_name='email_contacto',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='telefono',
            new_name='num_emergencia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.CharField(default='hola', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='trastorno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
