# Generated by Django 3.0.2 on 2020-03-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200324_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observaciones',
            name='curso',
        ),
    ]
