# Generated by Django 3.0.2 on 2020-03-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200320_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='foto',
        ),
    ]
