# Generated by Django 3.0.2 on 2020-03-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200324_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='ramos',
            new_name='ramo',
        ),
    ]
