# Generated by Django 3.0.2 on 2020-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200324_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apoderado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombres',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='Estudiante', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='Profesor', max_length=200),
            preserve_default=False,
        ),
    ]
