# Generated by Django 3.0.2 on 2020-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_profesor_nom_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='artes',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='ciencia',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='ed_fisica',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='historia',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='ingles',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='lenguaje',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='matematica',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='musica',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='taller',
            field=models.CharField(default='cambiar', max_length=50),
            preserve_default=False,
        ),
    ]
