# Generated by Django 3.0.2 on 2020-03-21 22:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20200321_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='ramos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('matematica', 'Matematica'), ('lenguaje', 'Lenguaje'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('ingles', 'Ingles'), ('artes', 'Artes'), ('taller', 'Taller'), ('musica', 'Musica'), ('ed_fisica', 'Ed. Fisica')], default='matematica', max_length=73),
        ),
    ]
