# Generated by Django 3.0.2 on 2020-03-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20200322_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
